name: "Code check"

on:
  workflow_call:
  push:
    branches:
      - "main"

  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "composer.json"
      - "ecs.php"
      - "rector.php"
      - "phpstan.neon"
      - "phpunit.xml"

concurrency:
  group: php-get-typed-value-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    name: "Code check"
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@7562253bdc3769847417e3476b501e7126f5d2c0
    secrets: inherit

  tests:
    name: "Run tests"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@91be5bbf6aca80f54548ec1bddc7c9ced6efb78f
    with:
      gistID: ${{ vars.GIST_ID }}
      gistOnPhpVersion: "8.2"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  tests_no_frameworks:
    name: "Run tests without Frameworks"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@91be5bbf6aca80f54548ec1bddc7c9ced6efb78f
    with:
      phpVersion: "${{ matrix.phpVersion }}"
      composerRemove: "--dev laravel/framework orchestra/testbench"
      dirsRemove: "tests/Laravel"

