on:
  pull_request:
  push:
    branches:
      - "*"
      - "!gh-pages"

jobs:
  run:
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@main
    secrets: inherit
    with:
      gistID: 11b884c06da0bf9116ae763d23438ecb
